// Données des caractères Hiragana et Katakana
const hiraganaData = {
    basic: [
        { char: 'あ', romaji: 'a' }, { char: 'い', romaji: 'i' }, { char: 'う', romaji: 'u' },
        { char: 'え', romaji: 'e' }, { char: 'お', romaji: 'o' }
    ],
    k: [
        { char: 'か', romaji: 'ka' }, { char: 'き', romaji: 'ki' }, { char: 'く', romaji: 'ku' },
        { char: 'け', romaji: 'ke' }, { char: 'こ', romaji: 'ko' }
    ],
    s: [
        { char: 'さ', romaji: 'sa' }, { char: 'し', romaji: 'shi' }, { char: 'す', romaji: 'su' },
        { char: 'せ', romaji: 'se' }, { char: 'そ', romaji: 'so' }
    ],
    t: [
        { char: 'た', romaji: 'ta' }, { char: 'ち', romaji: 'chi' }, { char: 'つ', romaji: 'tsu' },
        { char: 'て', romaji: 'te' }, { char: 'と', romaji: 'to' }
    ],
    n: [
        { char: 'な', romaji: 'na' }, { char: 'に', romaji: 'ni' }, { char: 'ぬ', romaji: 'nu' },
        { char: 'ね', romaji: 'ne' }, { char: 'の', romaji: 'no' }
    ],
    h: [
        { char: 'は', romaji: 'ha' }, { char: 'ひ', romaji: 'hi' }, { char: 'ふ', romaji: 'fu' },
        { char: 'へ', romaji: 'he' }, { char: 'ほ', romaji: 'ho' }
    ],
    m: [
        { char: 'ま', romaji: 'ma' }, { char: 'み', romaji: 'mi' }, { char: 'む', romaji: 'mu' },
        { char: 'め', romaji: 'me' }, { char: 'も', romaji: 'mo' }
    ],
    y: [
        { char: 'や', romaji: 'ya' }, { char: 'ゆ', romaji: 'yu' }, { char: 'よ', romaji: 'yo' }
    ],
    r: [
        { char: 'ら', romaji: 'ra' }, { char: 'り', romaji: 'ri' }, { char: 'る', romaji: 'ru' },
        { char: 'れ', romaji: 're' }, { char: 'ろ', romaji: 'ro' }
    ],
    w: [
        { char: 'わ', romaji: 'wa' }, { char: 'を', romaji: 'wo' }, { char: 'ん', romaji: 'n' }
    ],
    g: [
        { char: 'が', romaji: 'ga' }, { char: 'ぎ', romaji: 'gi' }, { char: 'ぐ', romaji: 'gu' },
        { char: 'げ', romaji: 'ge' }, { char: 'ご', romaji: 'go' }
    ],
    z: [
        { char: 'ざ', romaji: 'za' }, { char: 'じ', romaji: 'ji' }, { char: 'ず', romaji: 'zu' },
        { char: 'ぜ', romaji: 'ze' }, { char: 'ぞ', romaji: 'zo' }
    ],
    d: [
        { char: 'だ', romaji: 'da' }, { char: 'ぢ', romaji: 'ji' }, { char: 'づ', romaji: 'zu' },
        { char: 'で', romaji: 'de' }, { char: 'ど', romaji: 'do' }
    ],
    b: [
        { char: 'ば', romaji: 'ba' }, { char: 'び', romaji: 'bi' }, { char: 'ぶ', romaji: 'bu' },
        { char: 'べ', romaji: 'be' }, { char: 'ぼ', romaji: 'bo' }
    ],
    p: [
        { char: 'ぱ', romaji: 'pa' }, { char: 'ぴ', romaji: 'pi' }, { char: 'ぷ', romaji: 'pu' },
        { char: 'ぺ', romaji: 'pe' }, { char: 'ぽ', romaji: 'po' }
    ],
    kya: [
        { char: 'きゃ', romaji: 'kya' }, { char: 'きゅ', romaji: 'kyu' }, { char: 'きょ', romaji: 'kyo' }
    ],
    sha: [
        { char: 'しゃ', romaji: 'sha' }, { char: 'しゅ', romaji: 'shu' }, { char: 'しょ', romaji: 'sho' }
    ],
    cha: [
        { char: 'ちゃ', romaji: 'cha' }, { char: 'ちゅ', romaji: 'chu' }, { char: 'ちょ', romaji: 'cho' }
    ],
    nya: [
        { char: 'にゃ', romaji: 'nya' }, { char: 'にゅ', romaji: 'nyu' }, { char: 'にょ', romaji: 'nyo' }
    ],
    hya: [
        { char: 'ひゃ', romaji: 'hya' }, { char: 'ひゅ', romaji: 'hyu' }, { char: 'ひょ', romaji: 'hyo' }
    ],
    mya: [
        { char: 'みゃ', romaji: 'mya' }, { char: 'みゅ', romaji: 'myu' }, { char: 'みょ', romaji: 'myo' }
    ],
    rya: [
        { char: 'りゃ', romaji: 'rya' }, { char: 'りゅ', romaji: 'ryu' }, { char: 'りょ', romaji: 'ryo' }
    ],
    gya: [
        { char: 'ぎゃ', romaji: 'gya' }, { char: 'ぎゅ', romaji: 'gyu' }, { char: 'ぎょ', romaji: 'gyo' }
    ],
    ja: [
        { char: 'じゃ', romaji: 'ja' }, { char: 'じゅ', romaji: 'ju' }, { char: 'じょ', romaji: 'jo' }
    ],
    bya: [
        { char: 'びゃ', romaji: 'bya' }, { char: 'びゅ', romaji: 'byu' }, { char: 'びょ', romaji: 'byo' }
    ],
    pya: [
        { char: 'ぴゃ', romaji: 'pya' }, { char: 'ぴゅ', romaji: 'pyu' }, { char: 'ぴょ', romaji: 'pyo' }
    ]
};

const katakanaData = {
    basic: [
        { char: 'ア', romaji: 'a' }, { char: 'イ', romaji: 'i' }, { char: 'ウ', romaji: 'u' },
        { char: 'エ', romaji: 'e' }, { char: 'オ', romaji: 'o' }
    ],
    k: [
        { char: 'カ', romaji: 'ka' }, { char: 'キ', romaji: 'ki' }, { char: 'ク', romaji: 'ku' },
        { char: 'ケ', romaji: 'ke' }, { char: 'コ', romaji: 'ko' }
    ],
    s: [
        { char: 'サ', romaji: 'sa' }, { char: 'シ', romaji: 'shi' }, { char: 'ス', romaji: 'su' },
        { char: 'セ', romaji: 'se' }, { char: 'ソ', romaji: 'so' }
    ],
    t: [
        { char: 'タ', romaji: 'ta' }, { char: 'チ', romaji: 'chi' }, { char: 'ツ', romaji: 'tsu' },
        { char: 'テ', romaji: 'te' }, { char: 'ト', romaji: 'to' }
    ],
    n: [
        { char: 'ナ', romaji: 'na' }, { char: 'ニ', romaji: 'ni' }, { char: 'ヌ', romaji: 'nu' },
        { char: 'ネ', romaji: 'ne' }, { char: 'ノ', romaji: 'no' }
    ],
    h: [
        { char: 'ハ', romaji: 'ha' }, { char: 'ヒ', romaji: 'hi' }, { char: 'フ', romaji: 'fu' },
        { char: 'ヘ', romaji: 'he' }, { char: 'ホ', romaji: 'ho' }
    ],
    m: [
        { char: 'マ', romaji: 'ma' }, { char: 'ミ', romaji: 'mi' }, { char: 'ム', romaji: 'mu' },
        { char: 'メ', romaji: 'me' }, { char: 'モ', romaji: 'mo' }
    ],
    y: [
        { char: 'ヤ', romaji: 'ya' }, { char: 'ユ', romaji: 'yu' }, { char: 'ヨ', romaji: 'yo' }
    ],
    r: [
        { char: 'ラ', romaji: 'ra' }, { char: 'リ', romaji: 'ri' }, { char: 'ル', romaji: 'ru' },
        { char: 'レ', romaji: 're' }, { char: 'ロ', romaji: 'ro' }
    ],
    w: [
        { char: 'ワ', romaji: 'wa' }, { char: 'ヲ', romaji: 'wo' }, { char: 'ン', romaji: 'n' }
    ],
    g: [
        { char: 'ガ', romaji: 'ga' }, { char: 'ギ', romaji: 'gi' }, { char: 'グ', romaji: 'gu' },
        { char: 'ゲ', romaji: 'ge' }, { char: 'ゴ', romaji: 'go' }
    ],
    z: [
        { char: 'ザ', romaji: 'za' }, { char: 'ジ', romaji: 'ji' }, { char: 'ズ', romaji: 'zu' },
        { char: 'ゼ', romaji: 'ze' }, { char: 'ゾ', romaji: 'zo' }
    ],
    d: [
        { char: 'ダ', romaji: 'da' }, { char: 'ヂ', romaji: 'ji' }, { char: 'ヅ', romaji: 'zu' },
        { char: 'デ', romaji: 'de' }, { char: 'ド', romaji: 'do' }
    ],
    b: [
        { char: 'バ', romaji: 'ba' }, { char: 'ビ', romaji: 'bi' }, { char: 'ブ', romaji: 'bu' },
        { char: 'ベ', romaji: 'be' }, { char: 'ボ', romaji: 'bo' }
    ],
    p: [
        { char: 'パ', romaji: 'pa' }, { char: 'ピ', romaji: 'pi' }, { char: 'プ', romaji: 'pu' },
        { char: 'ペ', romaji: 'pe' }, { char: 'ポ', romaji: 'po' }
    ],
    kya: [
        { char: 'キャ', romaji: 'kya' }, { char: 'キュ', romaji: 'kyu' }, { char: 'キョ', romaji: 'kyo' }
    ],
    sha: [
        { char: 'シャ', romaji: 'sha' }, { char: 'シュ', romaji: 'shu' }, { char: 'ショ', romaji: 'sho' }
    ],
    cha: [
        { char: 'チャ', romaji: 'cha' }, { char: 'チュ', romaji: 'chu' }, { char: 'チョ', romaji: 'cho' }
    ],
    nya: [
        { char: 'ニャ', romaji: 'nya' }, { char: 'ニュ', romaji: 'nyu' }, { char: 'ニョ', romaji: 'nyo' }
    ],
    hya: [
        { char: 'ヒャ', romaji: 'hya' }, { char: 'ヒュ', romaji: 'hyu' }, { char: 'ヒョ', romaji: 'hyo' }
    ],
    mya: [
        { char: 'ミャ', romaji: 'mya' }, { char: 'ミュ', romaji: 'myu' }, { char: 'ミョ', romaji: 'myo' }
    ],
    rya: [
        { char: 'リャ', romaji: 'rya' }, { char: 'リュ', romaji: 'ryu' }, { char: 'リョ', romaji: 'ryo' }
    ],
    gya: [
        { char: 'ギャ', romaji: 'gya' }, { char: 'ギュ', romaji: 'gyu' }, { char: 'ギョ', romaji: 'gyo' }
    ],
    ja: [
        { char: 'ジャ', romaji: 'ja' }, { char: 'ジュ', romaji: 'ju' }, { char: 'ジョ', romaji: 'jo' }
    ],
    bya: [
        { char: 'ビャ', romaji: 'bya' }, { char: 'ビュ', romaji: 'byu' }, { char: 'ビョ', romaji: 'byo' }
    ],
    pya: [
        { char: 'ピャ', romaji: 'pya' }, { char: 'ピュ', romaji: 'pyu' }, { char: 'ピョ', romaji: 'pyo' }
    ]
};

// Mots Hiragana par niveau JLPT
const hiraganaWords = {
    n5: [
        { word: 'あお', romaji: 'ao', meaning: 'bleu', english: 'blue' },
        { word: 'あか', romaji: 'aka', meaning: 'rouge', english: 'red' },
        { word: 'あき', romaji: 'aki', meaning: 'automne', english: 'autumn' },
        { word: 'あさ', romaji: 'asa', meaning: 'matin', english: 'morning' },
        { word: 'あし', romaji: 'ashi', meaning: 'pied', english: 'foot' },
        { word: 'いえ', romaji: 'ie', meaning: 'maison', english: 'house' },
        { word: 'いけ', romaji: 'ike', meaning: 'étang', english: 'pond' },
        { word: 'いす', romaji: 'isu', meaning: 'chaise', english: 'chair' },
        { word: 'うえ', romaji: 'ue', meaning: 'dessus', english: 'above' },
        { word: 'うし', romaji: 'ushi', meaning: 'vache', english: 'cow' },
        { word: 'えき', romaji: 'eki', meaning: 'gare', english: 'station' },
        { word: 'おか', romaji: 'oka', meaning: 'colline', english: 'hill' },
        { word: 'おかね', romaji: 'okane', meaning: 'argent', english: 'money' },
        { word: 'かお', romaji: 'kao', meaning: 'visage', english: 'face' },
        { word: 'かき', romaji: 'kaki', meaning: 'huître', english: 'oyster' },
        { word: 'かね', romaji: 'kane', meaning: 'cloche', english: 'bell' },
        { word: 'き', romaji: 'ki', meaning: 'arbre', english: 'tree' },
        { word: 'きく', romaji: 'kiku', meaning: 'chrysanthème', english: 'chrysanthemum' },
        { word: 'くさ', romaji: 'kusa', meaning: 'herbe', english: 'grass' },
        { word: 'くつ', romaji: 'kutsu', meaning: 'chaussures', english: 'shoes' },
        { word: 'け', romaji: 'ke', meaning: 'cheveux', english: 'hair' },
        { word: 'こえ', romaji: 'koe', meaning: 'voix', english: 'voice' },
        { word: 'さか', romaji: 'saka', meaning: 'pente', english: 'slope' },
        { word: 'さけ', romaji: 'sake', meaning: 'alcool', english: 'alcohol' },
        { word: 'しお', romaji: 'shio', meaning: 'sel', english: 'salt' },
        { word: 'すし', romaji: 'sushi', meaning: 'sushi', english: 'sushi' },
        { word: 'たき', romaji: 'taki', meaning: 'cascade', english: 'waterfall' },
        { word: 'たこ', romaji: 'tako', meaning: 'pieuvre', english: 'octopus' },
        { word: 'ちか', romaji: 'chika', meaning: 'sous-sol', english: 'basement' },
        { word: 'つき', romaji: 'tsuki', meaning: 'lune', english: 'moon' },
        { word: 'て', romaji: 'te', meaning: 'main', english: 'hand' },
        { word: 'とけい', romaji: 'tokei', meaning: 'horloge', english: 'clock' },
        { word: 'なか', romaji: 'naka', meaning: 'intérieur', english: 'inside' },
        { word: 'にく', romaji: 'niku', meaning: 'viande', english: 'meat' },
        { word: 'ねこ', romaji: 'neko', meaning: 'chat', english: 'cat' },
        { word: 'の', romaji: 'no', meaning: 'champ', english: 'field' },
        { word: 'はし', romaji: 'hashi', meaning: 'pont', english: 'bridge' },
        { word: 'はな', romaji: 'hana', meaning: 'fleur', english: 'flower' },
        { word: 'ひ', romaji: 'hi', meaning: 'feu', english: 'fire' },
        { word: 'ふね', romaji: 'fune', meaning: 'bateau', english: 'boat' },
        { word: 'へや', romaji: 'heya', meaning: 'chambre', english: 'room' },
        { word: 'ほし', romaji: 'hoshi', meaning: 'étoile', english: 'star' },
        { word: 'まえ', romaji: 'mae', meaning: 'devant', english: 'in front' },
        { word: 'みみ', romaji: 'mimi', meaning: 'oreille', english: 'ear' },
        { word: 'むし', romaji: 'mushi', meaning: 'insecte', english: 'insect' },
        { word: 'め', romaji: 'me', meaning: 'œil', english: 'eye' },
        { word: 'もも', romaji: 'momo', meaning: 'pêche', english: 'peach' },
        { word: 'やま', romaji: 'yama', meaning: 'montagne', english: 'mountain' },
        { word: 'ゆき', romaji: 'yuki', meaning: 'neige', english: 'snow' },
        { word: 'よる', romaji: 'yoru', meaning: 'nuit', english: 'night' },
        { word: 'らく', romaji: 'raku', meaning: 'confortable', english: 'comfortable' },
        { word: 'りんご', romaji: 'ringo', meaning: 'pomme', english: 'apple' },
        { word: 'るす', romaji: 'rusu', meaning: 'absence', english: 'absence' },
        { word: 'れい', romaji: 'rei', meaning: 'zéro', english: 'zero' },
        { word: 'ろく', romaji: 'roku', meaning: 'six', english: 'six' },
        { word: 'わか', romaji: 'waka', meaning: 'jeune', english: 'young' },
        { word: 'を', romaji: 'wo', meaning: 'particule', english: 'particle' }
    ],
    n4: [
        { word: 'あい', romaji: 'ai', meaning: 'amour', english: 'love' },
        { word: 'あく', romaji: 'aku', meaning: 'ouvrir', english: 'open' },
        { word: 'あつい', romaji: 'atsui', meaning: 'chaud', english: 'hot' },
        { word: 'あめ', romaji: 'ame', meaning: 'pluie', english: 'rain' },
        { word: 'あらう', romaji: 'arau', meaning: 'laver', english: 'wash' },
        { word: 'あるく', romaji: 'aruku', meaning: 'marcher', english: 'walk' },
        { word: 'いい', romaji: 'ii', meaning: 'bon', english: 'good' },
        { word: 'いか', romaji: 'ika', meaning: 'calmar', english: 'squid' },
        { word: 'いく', romaji: 'iku', meaning: 'aller', english: 'go' },
        { word: 'いぬ', romaji: 'inu', meaning: 'chien', english: 'dog' },
        { word: 'うま', romaji: 'uma', meaning: 'cheval', english: 'horse' },
        { word: 'うる', romaji: 'uru', meaning: 'vendre', english: 'sell' },
        { word: 'おおい', romaji: 'ooi', meaning: 'beaucoup', english: 'many' },
        { word: 'おきる', romaji: 'okiru', meaning: 'se lever', english: 'get up' },
        { word: 'おくる', romaji: 'okuru', meaning: 'envoyer', english: 'send' },
        { word: 'おと', romaji: 'oto', meaning: 'son', english: 'sound' },
        { word: 'おわる', romaji: 'owaru', meaning: 'finir', english: 'finish' },
        { word: 'かう', romaji: 'kau', meaning: 'acheter', english: 'buy' },
        { word: 'かえる', romaji: 'kaeru', meaning: 'retourner', english: 'return' },
        { word: 'かく', romaji: 'kaku', meaning: 'écrire', english: 'write' },
        { word: 'かた', romaji: 'kata', meaning: 'épaule', english: 'shoulder' },
        { word: 'かみ', romaji: 'kami', meaning: 'papier', english: 'paper' },
        { word: 'からい', romaji: 'karai', meaning: 'épicé', english: 'spicy' },
        { word: 'かるい', romaji: 'karui', meaning: 'léger', english: 'light' },
        { word: 'きく', romaji: 'kiku', meaning: 'écouter', english: 'listen' },
        { word: 'きる', romaji: 'kiru', meaning: 'couper', english: 'cut' },
        { word: 'くろ', romaji: 'kuro', meaning: 'noir', english: 'black' },
        { word: 'けす', romaji: 'kesu', meaning: 'éteindre', english: 'turn off' },
        { word: 'こい', romaji: 'koi', meaning: 'carp', english: 'carp' },
        { word: 'こたえる', romaji: 'kotaeru', meaning: 'répondre', english: 'answer' },
        { word: 'さく', romaji: 'saku', meaning: 'fleurir', english: 'bloom' },
        { word: 'さむい', romaji: 'samui', meaning: 'froid', english: 'cold' },
        { word: 'しぬ', romaji: 'shinu', meaning: 'mourir', english: 'die' },
        { word: 'しる', romaji: 'shiru', meaning: 'savoir', english: 'know' },
        { word: 'すく', romaji: 'suku', meaning: 'creuser', english: 'dig' },
        { word: 'すむ', romaji: 'sumu', meaning: 'habiter', english: 'live' },
        { word: 'たかい', romaji: 'takai', meaning: 'haut/cher', english: 'high/expensive' },
        { word: 'たつ', romaji: 'tatsu', meaning: 'se lever', english: 'get up' },
        { word: 'ちかい', romaji: 'chikai', meaning: 'proche', english: 'close' },
        { word: 'つく', romaji: 'tsuku', meaning: 'arriver', english: 'arrive' },
        { word: 'つくる', romaji: 'tsukuru', meaning: 'créer', english: 'create' },
        { word: 'てる', romaji: 'teru', meaning: 'briller', english: 'shine' },
        { word: 'とる', romaji: 'toru', meaning: 'prendre', english: 'take' },
        { word: 'ながい', romaji: 'nagai', meaning: 'long', english: 'long' },
        { word: 'なく', romaji: 'naku', meaning: 'pleurer', english: 'cry' },
        { word: 'なつ', romaji: 'natsu', meaning: 'été', english: 'summer' },
        { word: 'にる', romaji: 'niru', meaning: 'bouillir', english: 'boil' },
        { word: 'ぬる', romaji: 'nuru', meaning: 'peindre', english: 'paint' },
        { word: 'ねる', romaji: 'neru', meaning: 'dormir', english: 'sleep' },
        { word: 'のむ', romaji: 'nomu', meaning: 'boire', english: 'drink' },
        { word: 'はいる', romaji: 'hairu', meaning: 'entrer', english: 'enter' },
        { word: 'はしる', romaji: 'hashiru', meaning: 'courir', english: 'run' },
        { word: 'はなす', romaji: 'hanasu', meaning: 'parler', english: 'speak' },
        { word: 'ひく', romaji: 'hiku', meaning: 'tirer', english: 'pull' },
        { word: 'ふく', romaji: 'fuku', meaning: 'souffler', english: 'blow' },
        { word: 'ふる', romaji: 'furu', meaning: 'tomber (pluie)', english: 'fall (rain)' },
        { word: 'へる', romaji: 'heru', meaning: 'diminuer', english: 'decrease' },
        { word: 'ほしい', romaji: 'hoshii', meaning: 'vouloir', english: 'want' },
        { word: 'まつ', romaji: 'matsu', meaning: 'attendre', english: 'wait' },
        { word: 'みる', romaji: 'miru', meaning: 'voir', english: 'see' },
        { word: 'むかう', romaji: 'mukau', meaning: 'faire face', english: 'face' },
        { word: 'め', romaji: 'me', meaning: 'œil', english: 'eye' },
        { word: 'もつ', romaji: 'motsu', meaning: 'tenir', english: 'hold' },
        { word: 'やる', romaji: 'yaru', meaning: 'faire', english: 'do' },
        { word: 'ゆく', romaji: 'yuku', meaning: 'aller', english: 'go' },
        { word: 'よむ', romaji: 'yomu', meaning: 'lire', english: 'read' },
        { word: 'らく', romaji: 'raku', meaning: 'confortable', english: 'comfortable' },
        { word: 'りる', romaji: 'riru', meaning: 'se lever', english: 'get up' },
        { word: 'るす', romaji: 'rusu', meaning: 'absence', english: 'absence' },
        { word: 'れい', romaji: 'rei', meaning: 'exemple', english: 'example' },
        { word: 'ろく', romaji: 'roku', meaning: 'six', english: 'six' },
        { word: 'わかる', romaji: 'wakaru', meaning: 'comprendre', english: 'understand' },
        { word: 'わるい', romaji: 'warui', meaning: 'mauvais', english: 'bad' }
    ],
    n3: [
        { word: 'あがる', romaji: 'agaru', meaning: 'monter', english: 'monter' },
        { word: 'あける', romaji: 'akeru', meaning: 'ouvrir', english: 'open' },
        { word: 'あつめる', romaji: 'atsumeru', meaning: 'collecter', english: 'collecter' },
        { word: 'あらう', romaji: 'arau', meaning: 'laver', english: 'wash' },
        { word: 'あらわれる', romaji: 'arawareru', meaning: 'apparaître', english: 'apparaître' },
        { word: 'いれる', romaji: 'ireru', meaning: 'mettre', english: 'mettre' },
        { word: 'うごく', romaji: 'ugoku', meaning: 'bouger', english: 'bouger' },
        { word: 'うつ', romaji: 'utsu', meaning: 'frapper', english: 'frapper' },
        { word: 'おきる', romaji: 'okiru', meaning: 'se lever', english: 'get up' },
        { word: 'おくる', romaji: 'okuru', meaning: 'envoyer', english: 'send' },
        { word: 'おちる', romaji: 'ochiru', meaning: 'tomber', english: 'tomber' },
        { word: 'おとす', romaji: 'otosu', meaning: 'laisser tomber', english: 'laisser tomber' },
        { word: 'おぼえる', romaji: 'oboeru', meaning: 'se souvenir', english: 'se souvenir' },
        { word: 'かえる', romaji: 'kaeru', meaning: 'changer', english: 'changer' },
        { word: 'かける', romaji: 'kakeru', meaning: 'appeler', english: 'appeler' },
        { word: 'かたづける', romaji: 'katadzukeru', meaning: 'ranger', english: 'ranger' },
        { word: 'かぶる', romaji: 'kaburu', meaning: 'porter (chapeau)', english: 'porter (chapeau)' },
        { word: 'きえる', romaji: 'kieru', meaning: 'disparaître', english: 'disparaître' },
        { word: 'きる', romaji: 'kiru', meaning: 'porter', english: 'porter' },
        { word: 'くばる', romaji: 'kubaru', meaning: 'distribuer', english: 'distribuer' },
        { word: 'くれる', romaji: 'kureru', meaning: 'donner', english: 'donner' },
        { word: 'こたえる', romaji: 'kotaeru', meaning: 'répondre', english: 'answer' },
        { word: 'こわす', romaji: 'kowasu', meaning: 'casser', english: 'casser' },
        { word: 'さがす', romaji: 'sagasu', meaning: 'chercher', english: 'chercher' },
        { word: 'さげる', romaji: 'sageru', meaning: 'baisser', english: 'baisser' },
        { word: 'さす', romaji: 'sasu', meaning: 'pointer', english: 'pointer' },
        { word: 'しめる', romaji: 'shimeru', meaning: 'fermer', english: 'fermer' },
        { word: 'しらせる', romaji: 'shiraseru', meaning: 'informer', english: 'informer' },
        { word: 'すむ', romaji: 'sumu', meaning: 'vivre', english: 'vivre' },
        { word: 'たおれる', romaji: 'taoreru', meaning: 'tomber', english: 'tomber' },
        { word: 'たすける', romaji: 'tasukeru', meaning: 'aider', english: 'aider' },
        { word: 'たつ', romaji: 'tatsu', meaning: 'se lever', english: 'get up' },
        { word: 'たのむ', romaji: 'tanomu', meaning: 'demander', english: 'demander' },
        { word: 'だす', romaji: 'dasu', meaning: 'sortir', english: 'sortir' },
        { word: 'つかう', romaji: 'tsukau', meaning: 'utiliser', english: 'utiliser' },
        { word: 'つかれる', romaji: 'tsukareru', meaning: 'être fatigué', english: 'être fatigué' },
        { word: 'つける', romaji: 'tsukeru', meaning: 'allumer', english: 'allumer' },
        { word: 'つたえる', romaji: 'tsutaeru', meaning: 'transmettre', english: 'transmettre' },
        { word: 'つづく', romaji: 'tsuzuku', meaning: 'continuer', english: 'continuer' },
        { word: 'つれる', romaji: 'tsureru', meaning: 'emmener', english: 'emmener' },
        { word: 'とおる', romaji: 'tooru', meaning: 'passer', english: 'passer' },
        { word: 'とまる', romaji: 'tomaru', meaning: 's\'arrêter' },
        { word: 'とる', romaji: 'toru', meaning: 'prendre', english: 'take' },
        { word: 'なおす', romaji: 'naosu', meaning: 'réparer', english: 'réparer' },
        { word: 'なくす', romaji: 'nakusu', meaning: 'perdre', english: 'perdre' },
        { word: 'ならぶ', romaji: 'narabu', meaning: 's\'aligner' },
        { word: 'ならべる', romaji: 'naraberu', meaning: 'aligner', english: 'aligner' },
        { word: 'にる', romaji: 'niru', meaning: 'ressembler', english: 'ressembler' },
        { word: 'のこる', romaji: 'nokoru', meaning: 'rester', english: 'rester' },
        { word: 'のる', romaji: 'noru', meaning: 'monter', english: 'monter' },
        { word: 'はいる', romaji: 'hairu', meaning: 'entrer', english: 'enter' },
        { word: 'はこぶ', romaji: 'hakobu', meaning: 'transporter', english: 'transporter' },
        { word: 'はなす', romaji: 'hanasu', meaning: 'parler', english: 'speak' },
        { word: 'はらう', romaji: 'harau', meaning: 'payer', english: 'payer' },
        { word: 'ひく', romaji: 'hiku', meaning: 'tirer', english: 'pull' },
        { word: 'ふる', romaji: 'furu', meaning: 'tomber', english: 'tomber' },
        { word: 'まがる', romaji: 'magaru', meaning: 'tourner', english: 'tourner' },
        { word: 'まつ', romaji: 'matsu', meaning: 'attendre', english: 'wait' },
        { word: 'まわす', romaji: 'mawasu', meaning: 'tourner', english: 'tourner' },
        { word: 'まわる', romaji: 'mawaru', meaning: 'tourner', english: 'tourner' },
        { word: 'みえる', romaji: 'mieru', meaning: 'être visible', english: 'être visible' },
        { word: 'みつける', romaji: 'mitsukeru', meaning: 'trouver', english: 'trouver' },
        { word: 'むかえる', romaji: 'mukaeru', meaning: 'accueillir', english: 'accueillir' },
        { word: 'もらう', romaji: 'morau', meaning: 'recevoir', english: 'recevoir' },
        { word: 'やる', romaji: 'yaru', meaning: 'faire', english: 'do' },
        { word: 'よぶ', romaji: 'yobu', meaning: 'appeler', english: 'appeler' },
        { word: 'よる', romaji: 'yoru', meaning: 'visiter', english: 'visiter' },
        { word: 'わかれる', romaji: 'wakareru', meaning: 'se séparer', english: 'se séparer' },
        { word: 'わすれる', romaji: 'wasureru', meaning: 'oublier', english: 'oublier' }
    ],
    n2: [
        { word: 'あきらめる', romaji: 'akirameru', meaning: 'abandonner', english: 'abandonner' },
        { word: 'あつかう', romaji: 'atsukau', meaning: 'traiter', english: 'traiter' },
        { word: 'あつまる', romaji: 'atsumaru', meaning: 'se rassembler', english: 'se rassembler' },
        { word: 'あやまる', romaji: 'ayamaru', meaning: 's\'excuser' },
        { word: 'いじめる', romaji: 'ijimeru', meaning: 'intimider', english: 'intimider' },
        { word: 'いのる', romaji: 'inoru', meaning: 'prier', english: 'prier' },
        { word: 'うけとる', romaji: 'uketoru', meaning: 'recevoir', english: 'recevoir' },
        { word: 'うたがう', romaji: 'utagau', meaning: 'douter', english: 'douter' },
        { word: 'うつす', romaji: 'utsusu', meaning: 'copier', english: 'copier' },
        { word: 'うまれる', romaji: 'umareru', meaning: 'naître', english: 'naître' },
        { word: 'おいかける', romaji: 'oikakeru', meaning: 'poursuivre', english: 'poursuivre' },
        { word: 'おくれる', romaji: 'okureru', meaning: 'être en retard', english: 'être en retard' },
        { word: 'おどる', romaji: 'odoru', meaning: 'danser', english: 'danser' },
        { word: 'おもいだす', romaji: 'omoidasu', meaning: 'se souvenir', english: 'se souvenir' },
        { word: 'かえす', romaji: 'kaesu', meaning: 'retourner', english: 'return' },
        { word: 'かくにんする', romaji: 'kakunin suru', meaning: 'confirmer', english: 'confirmer' },
        { word: 'かたる', romaji: 'kataru', meaning: 'raconter', english: 'raconter' },
        { word: 'かわかす', romaji: 'kawakasu', meaning: 'sécher', english: 'sécher' },
        { word: 'きこえる', romaji: 'kikoeru', meaning: 'être audible', english: 'être audible' },
        { word: 'きづく', romaji: 'kidzuku', meaning: 'remarquer', english: 'remarquer' },
        { word: 'きまる', romaji: 'kimaru', meaning: 'être décidé', english: 'être décidé' },
        { word: 'きめる', romaji: 'kimeru', meaning: 'décider', english: 'décider' },
        { word: 'くらべる', romaji: 'kuraberu', meaning: 'comparer', english: 'comparer' },
        { word: 'けす', romaji: 'kesu', meaning: 'éteindre', english: 'turn off' },
        { word: 'こまる', romaji: 'komaru', meaning: 'être en difficulté', english: 'être en difficulté' },
        { word: 'さがる', romaji: 'sagaru', meaning: 'descendre', english: 'descendre' },
        { word: 'さしあげる', romaji: 'sashiageru', meaning: 'donner (humble)', english: 'donner (humble)' },
        { word: 'さそう', romaji: 'sasou', meaning: 'inviter', english: 'inviter' },
        { word: 'しあがる', romaji: 'shiagaru', meaning: 'être terminé', english: 'être terminé' },
        { word: 'しかる', romaji: 'shikaru', meaning: 'gronder', english: 'gronder' },
        { word: 'しらべる', romaji: 'shiraberu', meaning: 'enquêter', english: 'enquêter' },
        { word: 'すてる', romaji: 'suteru', meaning: 'jeter', english: 'jeter' },
        { word: 'すむ', romaji: 'sumu', meaning: 'vivre', english: 'vivre' },
        { word: 'そだてる', romaji: 'sodateru', meaning: 'élever', english: 'élever' },
        { word: 'そろう', romaji: 'sorou', meaning: 'être complet', english: 'être complet' },
        { word: 'たずねる', romaji: 'tazuneru', meaning: 'visiter', english: 'visiter' },
        { word: 'たのしむ', romaji: 'tanoshimu', meaning: 'profiter', english: 'profiter' },
        { word: 'だまる', romaji: 'damaru', meaning: 'se taire', english: 'se taire' },
        { word: 'ちがう', romaji: 'chigau', meaning: 'différer', english: 'différer' },
        { word: 'つかまる', romaji: 'tsukamaru', meaning: 'être attrapé', english: 'être attrapé' },
        { word: 'つかむ', romaji: 'tsukamu', meaning: 'saisir', english: 'saisir' },
        { word: 'つづける', romaji: 'tsuzukeru', meaning: 'continuer', english: 'continuer' },
        { word: 'つとめる', romaji: 'tsutomeru', meaning: 'travailler', english: 'travailler' },
        { word: 'とおす', romaji: 'toosu', meaning: 'faire passer', english: 'faire passer' },
        { word: 'とどける', romaji: 'todokeru', meaning: 'livrer', english: 'livrer' },
        { word: 'とまる', romaji: 'tomaru', meaning: 's\'arrêter' },
        { word: 'とりかえる', romaji: 'torikaeru', meaning: 'échanger', english: 'échanger' },
        { word: 'ながれる', romaji: 'nagareru', meaning: 'couler', english: 'couler' },
        { word: 'なくなる', romaji: 'nakunaru', meaning: 'disparaître', english: 'disparaître' },
        { word: 'なげる', romaji: 'nageru', meaning: 'lancer', english: 'lancer' },
        { word: 'なれる', romaji: 'nareru', meaning: 's\'habituer' },
        { word: 'にげる', romaji: 'nigeru', meaning: 'fuir', english: 'fuir' },
        { word: 'のこす', romaji: 'nokosu', meaning: 'laisser', english: 'laisser' },
        { word: 'のぞむ', romaji: 'nozomu', meaning: 'souhaiter', english: 'souhaiter' },
        { word: 'はじまる', romaji: 'hajimaru', meaning: 'commencer', english: 'commencer' },
        { word: 'はじめる', romaji: 'hajimeru', meaning: 'commencer', english: 'commencer' },
        { word: 'はなれる', romaji: 'hanareru', meaning: 'se séparer', english: 'se séparer' },
        { word: 'ひえる', romaji: 'hieru', meaning: 'refroidir', english: 'refroidir' },
        { word: 'ふえる', romaji: 'fueru', meaning: 'augmenter', english: 'augmenter' },
        { word: 'ふさがる', romaji: 'fusagaru', meaning: 'être bloqué', english: 'être bloqué' },
        { word: 'ふるえる', romaji: 'furuueru', meaning: 'trembler', english: 'trembler' },
        { word: 'まにあう', romaji: 'maniau', meaning: 'être à temps', english: 'être à temps' },
        { word: 'まよう', romaji: 'mayou', meaning: 'être perdu', english: 'être perdu' },
        { word: 'みあげる', romaji: 'miageru', meaning: 'lever les yeux', english: 'lever les yeux' },
        { word: 'みおろす', romaji: 'miorosu', meaning: 'regarder en bas', english: 'regarder en bas' },
        { word: 'みつかる', romaji: 'mitsukaru', meaning: 'être trouvé', english: 'être trouvé' },
        { word: 'むかう', romaji: 'mukau', meaning: 'faire face', english: 'face' },
        { word: 'むすぶ', romaji: 'musubu', meaning: 'lier', english: 'lier' },
        { word: 'めざす', romaji: 'mezasu', meaning: 'viser', english: 'viser' },
        { word: 'もどる', romaji: 'modoru', meaning: 'retourner', english: 'return' },
        { word: 'やくす', romaji: 'yakusu', meaning: 'traduire', english: 'traduire' },
        { word: 'やめる', romaji: 'yameru', meaning: 'arrêter', english: 'arrêter' },
        { word: 'ゆるす', romaji: 'yurusu', meaning: 'permettre', english: 'permettre' },
        { word: 'よごれる', romaji: 'yogoreru', meaning: 'être sale', english: 'être sale' },
        { word: 'よろこぶ', romaji: 'yorokobu', meaning: 'se réjouir', english: 'se réjouir' },
        { word: 'わかす', romaji: 'wakasu', meaning: 'chauffer', english: 'chauffer' },
        { word: 'わらう', romaji: 'warau', meaning: 'rire', english: 'rire' }
    ],
    n1: [
        { word: 'あきらめる', romaji: 'akirameru', meaning: 'abandonner', english: 'abandonner' },
        { word: 'あつかう', romaji: 'atsukau', meaning: 'traiter', english: 'traiter' },
        { word: 'あやまる', romaji: 'ayamaru', meaning: 's\'excuser' },
        { word: 'いとなむ', romaji: 'itonamu', meaning: 'exploiter', english: 'exploiter' },
        { word: 'うけいれる', romaji: 'ukeireru', meaning: 'accepter', english: 'accepter' },
        { word: 'うったえる', romaji: 'uttaeru', meaning: 'porter plainte', english: 'porter plainte' },
        { word: 'うながす', romaji: 'unagasu', meaning: 'encourager', english: 'encourager' },
        { word: 'おいこす', romaji: 'oikosu', meaning: 'dépasser', english: 'dépasser' },
        { word: 'おかす', romaji: 'okasu', meaning: 'violer', english: 'violer' },
        { word: 'おぎなう', romaji: 'oginau', meaning: 'compenser', english: 'compenser' },
        { word: 'おとずれる', romaji: 'otozureru', meaning: 'visiter', english: 'visiter' },
        { word: 'おもいこむ', romaji: 'omoikomu', meaning: 'être convaincu', english: 'être convaincu' },
        { word: 'かかげる', romaji: 'kakageru', meaning: 'élever', english: 'élever' },
        { word: 'かさねる', romaji: 'kasaneru', meaning: 'empiler', english: 'empiler' },
        { word: 'かたむける', romaji: 'katamukeru', meaning: 'incliner', english: 'incliner' },
        { word: 'かなう', romaji: 'kanau', meaning: 'se réaliser', english: 'se réaliser' },
        { word: 'かまえる', romaji: 'kamaeru', meaning: 'se préparer', english: 'se préparer' },
        { word: 'かわす', romaji: 'kawasu', meaning: 'éviter', english: 'éviter' },
        { word: 'きかえる', romaji: 'kikaeru', meaning: 'changer', english: 'changer' },
        { word: 'きざむ', romaji: 'kizamu', meaning: 'sculpter', english: 'sculpter' },
        { word: 'きずく', romaji: 'kidzuku', meaning: 'construire', english: 'construire' },
        { word: 'きづく', romaji: 'kidzuku', meaning: 'remarquer', english: 'remarquer' },
        { word: 'きらう', romaji: 'kirau', meaning: 'détester', english: 'détester' },
        { word: 'くぐる', romaji: 'kuguru', meaning: 'passer sous', english: 'passer sous' },
        { word: 'くみたてる', romaji: 'kumitateru', meaning: 'assembler', english: 'assembler' },
        { word: 'くむ', romaji: 'kumu', meaning: 'puiser', english: 'puiser' },
        { word: 'けずる', romaji: 'kezuru', meaning: 'tailler', english: 'tailler' },
        { word: 'こころえる', romaji: 'kokoroeru', meaning: 'comprendre', english: 'understand' },
        { word: 'こしらえる', romaji: 'koshiraeru', meaning: 'créer', english: 'create' },
        { word: 'こだわる', romaji: 'kodawaru', meaning: 'insister', english: 'insister' },
        { word: 'こらえる', romaji: 'koraeru', meaning: 'supporter', english: 'supporter' },
        { word: 'さかのぼる', romaji: 'sakanoboru', meaning: 'remonter', english: 'remonter' },
        { word: 'さぐる', romaji: 'saguru', meaning: 'chercher', english: 'chercher' },
        { word: 'ささえる', romaji: 'sasaeru', meaning: 'soutenir', english: 'soutenir' },
        { word: 'さしだす', romaji: 'sashidasu', meaning: 'présenter', english: 'présenter' },
        { word: 'さとる', romaji: 'satoru', meaning: 'réaliser', english: 'réaliser' },
        { word: 'しのぶ', romaji: 'shinobu', meaning: 'endurer', english: 'endurer' },
        { word: 'しめす', romaji: 'shimesu', meaning: 'montrer', english: 'montrer' },
        { word: 'しめる', romaji: 'shimeru', meaning: 'fermer', english: 'fermer' },
        { word: 'すくう', romaji: 'sukuu', meaning: 'sauver', english: 'sauver' },
        { word: 'すすぐ', romaji: 'susugu', meaning: 'rincer', english: 'rincer' },
        { word: 'すてる', romaji: 'suteru', meaning: 'jeter', english: 'jeter' },
        { word: 'そなえる', romaji: 'sonaeru', meaning: 'préparer', english: 'préparer' },
        { word: 'そむく', romaji: 'somuku', meaning: 'désobéir', english: 'désobéir' },
        { word: 'たえる', romaji: 'taeru', meaning: 'endurer', english: 'endurer' },
        { word: 'たくわえる', romaji: 'takuwaeru', meaning: 'accumuler', english: 'accumuler' },
        { word: 'たしかめる', romaji: 'tashikameru', meaning: 'vérifier', english: 'vérifier' },
        { word: 'たずさわる', romaji: 'tazusawaru', meaning: 'participer', english: 'participer' },
        { word: 'たたえる', romaji: 'tataeru', meaning: 'louer', english: 'louer' },
        { word: 'たどる', romaji: 'tadoru', meaning: 'suivre', english: 'suivre' },
        { word: 'たのしむ', romaji: 'tanoshimu', meaning: 'profiter', english: 'profiter' },
        { word: 'たまわる', romaji: 'tamawaru', meaning: 'recevoir', english: 'recevoir' },
        { word: 'ためす', romaji: 'tamesu', meaning: 'essayer', english: 'essayer' },
        { word: 'だまる', romaji: 'damaru', meaning: 'se taire', english: 'se taire' },
        { word: 'ちかづく', romaji: 'chikadzuku', meaning: 'approcher', english: 'approcher' },
        { word: 'ちかよる', romaji: 'chikayoru', meaning: 's\'approcher' },
        { word: 'ついやす', romaji: 'tsuiyasu', meaning: 'dépenser', english: 'dépenser' },
        { word: 'つかえる', romaji: 'tsukaeru', meaning: 'être utile', english: 'être utile' },
        { word: 'つきあう', romaji: 'tsukiau', meaning: 'fréquenter', english: 'fréquenter' },
        { word: 'つくす', romaji: 'tsukusu', meaning: 'épuiser', english: 'épuiser' },
        { word: 'つたわる', romaji: 'tsutawaru', meaning: 'être transmis', english: 'être transmis' },
        { word: 'つとめる', romaji: 'tsutomeru', meaning: 'travailler', english: 'travailler' },
        { word: 'つらぬく', romaji: 'tsuranuku', meaning: 'percer', english: 'percer' },
        { word: 'てらす', romaji: 'terasu', meaning: 'éclairer', english: 'éclairer' },
        { word: 'とがめる', romaji: 'togameru', meaning: 'blâmer', english: 'blâmer' },
        { word: 'とぎれる', romaji: 'togireru', meaning: 'être interrompu', english: 'être interrompu' },
        { word: 'とげる', romaji: 'togeru', meaning: 'accomplir', english: 'accomplir' },
        { word: 'とじる', romaji: 'tojiru', meaning: 'fermer', english: 'fermer' },
        { word: 'ととのえる', romaji: 'totonoeru', meaning: 'préparer', english: 'préparer' },
        { word: 'とどまる', romaji: 'todomaru', meaning: 'rester', english: 'rester' },
        { word: 'とどめる', romaji: 'todomeru', meaning: 'limiter', english: 'limiter' },
        { word: 'とりくむ', romaji: 'torikumu', meaning: 's\'engager' },
        { word: 'とりしまる', romaji: 'torishimaru', meaning: 'gérer', english: 'gérer' },
        { word: 'とりつける', romaji: 'toritsukeru', meaning: 'installer', english: 'installer' },
        { word: 'とりもどす', romaji: 'torimodosu', meaning: 'récupérer', english: 'récupérer' },
        { word: 'なげく', romaji: 'nageku', meaning: 'se lamenter', english: 'se lamenter' },
        { word: 'なげる', romaji: 'nageru', meaning: 'lancer', english: 'lancer' },
        { word: 'なさけぶかい', romaji: 'nasakebukai', meaning: 'compassionné', english: 'compassionné' },
        { word: 'なじる', romaji: 'najiru', meaning: 'réprimander', english: 'réprimander' },
        { word: 'なぞる', romaji: 'nazoru', meaning: 'tracer', english: 'tracer' },
        { word: 'なだめる', romaji: 'nadameru', meaning: 'apaiser', english: 'apaiser' },
        { word: 'なつく', romaji: 'natsuku', meaning: 's\'attacher' },
        { word: 'なやむ', romaji: 'nayamu', meaning: 'se soucier', english: 'se soucier' },
        { word: 'なれる', romaji: 'nareru', meaning: 's\'habituer' },
        { word: 'にぎる', romaji: 'nigiru', meaning: 'serrer', english: 'serrer' },
        { word: 'にげる', romaji: 'nigeru', meaning: 'fuir', english: 'fuir' },
        { word: 'にらむ', romaji: 'niramu', meaning: 'fixer', english: 'fixer' },
        { word: 'ぬぐ', romaji: 'nugu', meaning: 'enlever', english: 'enlever' },
        { word: 'ねがう', romaji: 'negau', meaning: 'souhaiter', english: 'souhaiter' },
        { word: 'ねじる', romaji: 'nejiru', meaning: 'tordre', english: 'tordre' },
        { word: 'ねらう', romaji: 'nerau', meaning: 'viser', english: 'viser' },
        { word: 'のぞく', romaji: 'nozoku', meaning: 'regarder', english: 'regarder' },
        { word: 'のぞむ', romaji: 'nozomu', meaning: 'souhaiter', english: 'souhaiter' },
        { word: 'のりこえる', romaji: 'norikoeru', meaning: 'surmonter', english: 'surmonter' },
        { word: 'はかる', romaji: 'hakaru', meaning: 'mesurer', english: 'mesurer' },
        { word: 'はげます', romaji: 'hagemasu', meaning: 'encourager', english: 'encourager' },
        { word: 'はげむ', romaji: 'hagemu', meaning: 's\'efforcer' },
        { word: 'はじめる', romaji: 'hajimeru', meaning: 'commencer', english: 'commencer' },
        { word: 'はしる', romaji: 'hashiru', meaning: 'courir', english: 'run' },
        { word: 'はたらく', romaji: 'hataraku', meaning: 'travailler', english: 'travailler' },
        { word: 'はなす', romaji: 'hanasu', meaning: 'parler', english: 'speak' },
        { word: 'はやめる', romaji: 'hayameru', meaning: 'accélérer', english: 'accélérer' },
        { word: 'ひかえる', romaji: 'hikaeru', meaning: 's\'abstenir' },
        { word: 'ひきかえす', romaji: 'hikikaesu', meaning: 'retourner', english: 'return' },
        { word: 'ひきとめる', romaji: 'hikitomeru', meaning: 'retenir', english: 'retenir' },
        { word: 'ひく', romaji: 'hiku', meaning: 'tirer', english: 'pull' },
        { word: 'ひそむ', romaji: 'hisomu', meaning: 'se cacher', english: 'se cacher' },
        { word: 'ひらく', romaji: 'hiraku', meaning: 'ouvrir', english: 'open' },
        { word: 'ふかめる', romaji: 'fukameru', meaning: 'approfondir', english: 'approfondir' },
        { word: 'ふくらむ', romaji: 'fukuramu', meaning: 'gonfler', english: 'gonfler' },
        { word: 'ふさぐ', romaji: 'fusagu', meaning: 'boucher', english: 'boucher' },
        { word: 'ふるまう', romaji: 'furumau', meaning: 'se comporter', english: 'se comporter' },
        { word: 'へだてる', romaji: 'hedateru', meaning: 'séparer', english: 'séparer' },
        { word: 'へらす', romaji: 'herasu', meaning: 'réduire', english: 'réduire' },
        { word: 'ほえる', romaji: 'hoeru', meaning: 'aboyer', english: 'aboyer' },
        { word: 'ほころぶ', romaji: 'hokorobu', meaning: 's\'épanouir' },
        { word: 'ほろびる', romaji: 'horobiru', meaning: 'périr', english: 'périr' },
        { word: 'まかせる', romaji: 'makaseru', meaning: 'confier', english: 'confier' },
        { word: 'まかなう', romaji: 'makanau', meaning: 'financer', english: 'financer' },
        { word: 'まぎれる', romaji: 'magireru', meaning: 'se mélanger', english: 'se mélanger' },
        { word: 'まく', romaji: 'maku', meaning: 'semer', english: 'semer' },
        { word: 'まげる', romaji: 'mageru', meaning: 'plier', english: 'plier' },
        { word: 'まさつ', romaji: 'masatsu', meaning: 'friction', english: 'friction' },
        { word: 'まぜる', romaji: 'mazeru', meaning: 'mélanger', english: 'mélanger' },
        { word: 'またがる', romaji: 'matagaru', meaning: 'enjamber', english: 'enjamber' },
        { word: 'まつ', romaji: 'matsu', meaning: 'attendre', english: 'wait' },
        { word: 'まとまる', romaji: 'matomaru', meaning: 'être organisé', english: 'être organisé' },
        { word: 'まとめる', romaji: 'matomeru', meaning: 'organiser', english: 'organiser' },
        { word: 'まねく', romaji: 'maneku', meaning: 'inviter', english: 'inviter' },
        { word: 'まもる', romaji: 'mamoru', meaning: 'protéger', english: 'protéger' },
        { word: 'まよう', romaji: 'mayou', meaning: 'être perdu', english: 'être perdu' },
        { word: 'みあげる', romaji: 'miageru', meaning: 'lever les yeux', english: 'lever les yeux' },
        { word: 'みおとす', romaji: 'miotosu', meaning: 'manquer', english: 'manquer' },
        { word: 'みおろす', romaji: 'miorosu', meaning: 'regarder en bas', english: 'regarder en bas' },
        { word: 'みがく', romaji: 'migaku', meaning: 'polir', english: 'polir' },
        { word: 'みきわめる', romaji: 'mikiwameru', meaning: 'déterminer', english: 'déterminer' },
        { word: 'みこむ', romaji: 'mikomu', meaning: 'anticiper', english: 'anticiper' },
        { word: 'みすてる', romaji: 'misuteru', meaning: 'abandonner', english: 'abandonner' },
        { word: 'みだす', romaji: 'midasu', meaning: 'déranger', english: 'déranger' },
        { word: 'みつめる', romaji: 'mitsumeru', meaning: 'fixer', english: 'fixer' },
        { word: 'みとめる', romaji: 'mitomeru', meaning: 'reconnaître', english: 'reconnaître' },
        { word: 'みなす', romaji: 'minasu', meaning: 'considérer', english: 'considérer' },
        { word: 'みのがす', romaji: 'minogasu', meaning: 'manquer', english: 'manquer' },
        { word: 'みはる', romaji: 'miharu', meaning: 'surveiller', english: 'surveiller' },
        { word: 'みまもる', romaji: 'mimamoru', meaning: 'surveiller', english: 'surveiller' },
        { word: 'みまわす', romaji: 'mimawasu', meaning: 'regarder autour', english: 'regarder autour' },
        { word: 'みわたす', romaji: 'miwatasu', meaning: 'voir au loin', english: 'voir au loin' },
        { word: 'むかう', romaji: 'mukau', meaning: 'faire face', english: 'face' },
        { word: 'むかえる', romaji: 'mukaeru', meaning: 'accueillir', english: 'accueillir' },
        { word: 'むく', romaji: 'muku', meaning: 'faire face', english: 'face' },
        { word: 'むける', romaji: 'mukeru', meaning: 'tourner', english: 'tourner' },
        { word: 'むしる', romaji: 'mushiru', meaning: 'arracher', english: 'arracher' },
        { word: 'むすぶ', romaji: 'musubu', meaning: 'lier', english: 'lier' },
        { word: 'むらがる', romaji: 'muragaru', meaning: 'se rassembler', english: 'se rassembler' },
        { word: 'めぐる', romaji: 'meguru', meaning: 'tourner', english: 'tourner' },
        { word: 'めざす', romaji: 'mezasu', meaning: 'viser', english: 'viser' },
        { word: 'めだつ', romaji: 'medatsu', meaning: 'se démarquer', english: 'se démarquer' },
        { word: 'めんじる', romaji: 'menjiru', meaning: 'dédaigner', english: 'dédaigner' },
        { word: 'もうける', romaji: 'moukeru', meaning: 'gagner', english: 'gagner' },
        { word: 'もうしあげる', romaji: 'moushiageru', meaning: 'dire (humble)', english: 'dire (humble)' },
        { word: 'もうす', romaji: 'mousu', meaning: 'dire (humble)', english: 'dire (humble)' },
        { word: 'もえる', romaji: 'moeru', meaning: 'brûler', english: 'brûler' },
        { word: 'もがく', romaji: 'mogaku', meaning: 'se débattre', english: 'se débattre' },
        { word: 'もぎる', romaji: 'mogiru', meaning: 'cueillir', english: 'cueillir' },
        { word: 'もぐる', romaji: 'moguru', meaning: 'plonger', english: 'plonger' },
        { word: 'もたらす', romaji: 'motarasu', meaning: 'apporter', english: 'apporter' },
        { word: 'もてなす', romaji: 'motenasu', meaning: 'recevoir', english: 'recevoir' },
        { word: 'もとめる', romaji: 'motomeru', meaning: 'demander', english: 'demander' },
        { word: 'もとる', romaji: 'motoru', meaning: 'violer', english: 'violer' },
        { word: 'もどす', romaji: 'modosu', meaning: 'retourner', english: 'return' },
        { word: 'もらう', romaji: 'morau', meaning: 'recevoir', english: 'recevoir' },
        { word: 'やくだつ', romaji: 'yakudatsu', meaning: 'être utile', english: 'être utile' },
        { word: 'やしなう', romaji: 'yashinau', meaning: 'élever', english: 'élever' },
        { word: 'やすめる', romaji: 'yasumeru', meaning: 'reposer', english: 'reposer' },
        { word: 'やっつける', romaji: 'yattsukeru', meaning: 'battre', english: 'battre' },
        { word: 'やどる', romaji: 'yadoru', meaning: 'loger', english: 'loger' },
        { word: 'やぶる', romaji: 'yaburu', meaning: 'déchirer', english: 'déchirer' },
        { word: 'やむ', romaji: 'yamu', meaning: 'cesser', english: 'cesser' },
        { word: 'やめる', romaji: 'yameru', meaning: 'arrêter', english: 'arrêter' },
        { word: 'やわらげる', romaji: 'yawarageru', meaning: 'adoucir', english: 'adoucir' },
        { word: 'ゆうする', romaji: 'yuusuru', meaning: 'posséder', english: 'posséder' },
        { word: 'ゆがむ', romaji: 'yugamu', meaning: 'se déformer', english: 'se déformer' },
        { word: 'ゆする', romaji: 'yusuru', meaning: 'secouer', english: 'secouer' },
        { word: 'ゆだねる', romaji: 'yudaneru', meaning: 'confier', english: 'confier' },
        { word: 'ゆるがす', romaji: 'yurugasu', meaning: 'ébranler', english: 'ébranler' },
        { word: 'ゆるむ', romaji: 'yurumu', meaning: 'se détendre', english: 'se détendre' },
        { word: 'ゆるめる', romaji: 'yurumeru', meaning: 'relâcher', english: 'relâcher' },
        { word: 'ゆるす', romaji: 'yurusu', meaning: 'permettre', english: 'permettre' },
        { word: 'よごす', romaji: 'yogosu', meaning: 'salir', english: 'salir' },
        { word: 'よごれる', romaji: 'yogoreru', meaning: 'être sale', english: 'être sale' },
        { word: 'よそおう', romaji: 'yosou', meaning: 's\'habiller' },
        { word: 'よびかける', romaji: 'yobikakeru', meaning: 'appeler', english: 'appeler' },
        { word: 'よびだす', romaji: 'yobidasu', meaning: 'appeler', english: 'appeler' },
        { word: 'よぶ', romaji: 'yobu', meaning: 'appeler', english: 'appeler' },
        { word: 'よみがえる', romaji: 'yomigaeru', meaning: 'renaître', english: 'renaître' },
        { word: 'よむ', romaji: 'yomu', meaning: 'lire', english: 'read' },
        { word: 'よる', romaji: 'yoru', meaning: 'visiter', english: 'visiter' },
        { word: 'よろこぶ', romaji: 'yorokobu', meaning: 'se réjouir', english: 'se réjouir' },
        { word: 'よわまる', romaji: 'yowamaru', meaning: 's\'affaiblir' },
        { word: 'よわめる', romaji: 'yowameru', meaning: 'affaiblir', english: 'affaiblir' },
        { word: 'らく', romaji: 'raku', meaning: 'confortable', english: 'comfortable' },
        { word: 'りかいする', romaji: 'rikai suru', meaning: 'comprendre', english: 'understand' },
        { word: 'りようする', romaji: 'riyou suru', meaning: 'utiliser', english: 'utiliser' },
        { word: 'わかす', romaji: 'wakasu', meaning: 'chauffer', english: 'chauffer' },
        { word: 'わかれる', romaji: 'wakareru', meaning: 'se séparer', english: 'se séparer' },
        { word: 'わかる', romaji: 'wakaru', meaning: 'comprendre', english: 'understand' },
        { word: 'わく', romaji: 'waku', meaning: 'bouillonner', english: 'bouillonner' },
        { word: 'わける', romaji: 'wakeru', meaning: 'diviser', english: 'diviser' },
        { word: 'わずらう', romaji: 'wazurau', meaning: 'être troublé', english: 'être troublé' },
        { word: 'わらう', romaji: 'warau', meaning: 'rire', english: 'rire' },
        { word: 'われる', romaji: 'wareru', meaning: 'se casser', english: 'se casser' },
        { word: 'わる', romaji: 'waru', meaning: 'casser', english: 'casser' },
        { word: 'わる', romaji: 'waru', meaning: 'diviser', english: 'diviser' }
    ]
};

// Mots Katakana
const katakanaWords = {
    basic: [
        { word: 'アパート', romaji: 'apaato', meaning: 'appartement', english: 'appartement' },
        { word: 'アイスクリーム', romaji: 'aisukuriimu', meaning: 'glace', english: 'glace' },
        { word: 'アメリカ', romaji: 'amerika', meaning: 'Amérique', english: 'Amérique' },
        { word: 'イギリス', romaji: 'igirisu', meaning: 'Angleterre', english: 'Angleterre' },
        { word: 'エアコン', romaji: 'eakon', meaning: 'climatiseur', english: 'climatiseur' },
        { word: 'エレベーター', romaji: 'erebeetaa', meaning: 'ascenseur', english: 'ascenseur' },
        { word: 'オートバイ', romaji: 'ootobai', meaning: 'moto', english: 'moto' },
        { word: 'カード', romaji: 'kaado', meaning: 'carte', english: 'carte' },
        { word: 'カメラ', romaji: 'kamera', meaning: 'appareil photo', english: 'appareil photo' },
        { word: 'カレー', romaji: 'karee', meaning: 'curry', english: 'curry' },
        { word: 'キーボード', romaji: 'kiiboodo', meaning: 'clavier', english: 'clavier' },
        { word: 'コーヒー', romaji: 'koohii', meaning: 'café', english: 'café' },
        { word: 'コンピューター', romaji: 'konpyuutaa', meaning: 'ordinateur', english: 'ordinateur' },
        { word: 'サッカー', romaji: 'sakkaa', meaning: 'football', english: 'football' },
        { word: 'サンドイッチ', romaji: 'sandoicchi', meaning: 'sandwich', english: 'sandwich' },
        { word: 'シャツ', romaji: 'shatsu', meaning: 'chemise', english: 'chemise' },
        { word: 'スーパー', romaji: 'suupaa', meaning: 'supermarché', english: 'supermarché' },
        { word: 'スポーツ', romaji: 'supootsu', meaning: 'sport', english: 'sport' },
        { word: 'テーブル', romaji: 'teeburu', meaning: 'table', english: 'table' },
        { word: 'テレビ', romaji: 'terebi', meaning: 'télévision', english: 'télévision' },
        { word: 'トイレ', romaji: 'toire', meaning: 'toilettes', english: 'toilettes' },
        { word: 'ナイフ', romaji: 'naifu', meaning: 'couteau', english: 'couteau' },
        { word: 'ノート', romaji: 'nooto', meaning: 'cahier', english: 'cahier' },
        { word: 'パン', romaji: 'pan', meaning: 'pain', english: 'pain' },
        { word: 'パーティー', romaji: 'paatii', meaning: 'fête', english: 'fête' },
        { word: 'ハンバーガー', romaji: 'hanbaagaa', meaning: 'hamburger', english: 'hamburger' },
        { word: 'ビール', romaji: 'biiru', meaning: 'bière', english: 'bière' },
        { word: 'ピアノ', romaji: 'piano', meaning: 'piano', english: 'piano' },
        { word: 'フランス', romaji: 'furansu', meaning: 'France', english: 'France' },
        { word: 'ペン', romaji: 'pen', meaning: 'stylo', english: 'stylo' },
        { word: 'ホテル', romaji: 'hoteru', meaning: 'hôtel', english: 'hôtel' },
        { word: 'マンション', romaji: 'manshon', meaning: 'immeuble', english: 'immeuble' },
        { word: 'メニュー', romaji: 'menyuu', meaning: 'menu', english: 'menu' },
        { word: 'ラジオ', romaji: 'rajio', meaning: 'radio', english: 'radio' },
        { word: 'レストラン', romaji: 'resutoran', meaning: 'restaurant', english: 'restaurant' },
        { word: 'ロシア', romaji: 'roshia', meaning: 'Russie', english: 'Russie' }
    ],
    intermediate: [
        { word: 'アニメ', romaji: 'anime', meaning: 'anime', english: 'anime' },
        { word: 'インターネット', romaji: 'intaanetto', meaning: 'internet', english: 'internet' },
        { word: 'ウイルス', romaji: 'uirusu', meaning: 'virus', english: 'virus' },
        { word: 'エンジン', romaji: 'enjin', meaning: 'moteur', english: 'moteur' },
        { word: 'オフィス', romaji: 'ofisu', meaning: 'bureau', english: 'bureau' },
        { word: 'ガソリン', romaji: 'gasorin', meaning: 'essence', english: 'essence' },
        { word: 'ギター', romaji: 'gitaa', meaning: 'guitare', english: 'guitare' },
        { word: 'グラス', romaji: 'gurasu', meaning: 'verre', english: 'verre' },
        { word: 'クリスマス', romaji: 'kurisumasu', meaning: 'Noël', english: 'Noël' },
        { word: 'ゲーム', romaji: 'geemu', meaning: 'jeu', english: 'jeu' },
        { word: 'コピー', romaji: 'kopii', meaning: 'copie', english: 'copie' },
        { word: 'サイズ', romaji: 'saizu', meaning: 'taille', english: 'taille' },
        { word: 'サラダ', romaji: 'sarada', meaning: 'salade', english: 'salade' },
        { word: 'シート', romaji: 'shiito', meaning: 'siège', english: 'siège' },
        { word: 'スカート', romaji: 'sukaato', meaning: 'jupe', english: 'jupe' },
        { word: 'セーター', romaji: 'seetaa', meaning: 'pull', english: 'pull' },
        { word: 'ソファー', romaji: 'sofaa', meaning: 'canapé', english: 'canapé' },
        { word: 'タクシー', romaji: 'takushii', meaning: 'taxi', english: 'taxi' },
        { word: 'チケット', romaji: 'chiketto', meaning: 'billet', english: 'billet' },
        { word: 'ツアー', romaji: 'tsuaa', meaning: 'tour', english: 'tour' },
        { word: 'デザイン', romaji: 'dezain', meaning: 'design', english: 'design' },
        { word: 'ドア', romaji: 'doa', meaning: 'porte', english: 'porte' },
        { word: 'ナンバー', romaji: 'nanbaa', meaning: 'numéro', english: 'numéro' },
        { word: 'ニュース', romaji: 'nyuusu', meaning: 'nouvelles', english: 'nouvelles' },
        { word: 'ネクタイ', romaji: 'nekutai', meaning: 'cravate', english: 'cravate' },
        { word: 'バス', romaji: 'basu', meaning: 'bus', english: 'bus' },
        { word: 'バッグ', romaji: 'baggu', meaning: 'sac', english: 'sac' },
        { word: 'パスポート', romaji: 'pasupooto', meaning: 'passeport', english: 'passeport' },
        { word: 'ヒーター', romaji: 'hiitaa', meaning: 'chauffage', english: 'chauffage' },
        { word: 'ファックス', romaji: 'fakkusu', meaning: 'fax', english: 'fax' },
        { word: 'フィルム', romaji: 'firumu', meaning: 'film', english: 'film' },
        { word: 'ブーツ', romaji: 'buutsu', meaning: 'bottes', english: 'bottes' },
        { word: 'プラス', romaji: 'purasu', meaning: 'plus', english: 'plus' },
        { word: 'プログラム', romaji: 'puroguramu', meaning: 'programme', english: 'programme' },
        { word: 'ベッド', romaji: 'beddo', meaning: 'lit', english: 'lit' },
        { word: 'ペット', romaji: 'petto', meaning: 'animal de compagnie', english: 'animal de compagnie' },
        { word: 'ボタン', romaji: 'botan', meaning: 'bouton', english: 'bouton' },
        { word: 'ポスト', romaji: 'posuto', meaning: 'boîte aux lettres', english: 'boîte aux lettres' },
        { word: 'マウス', romaji: 'mausu', meaning: 'souris', english: 'souris' },
        { word: 'ミルク', romaji: 'miruku', meaning: 'lait', english: 'lait' },
        { word: 'メール', romaji: 'meeru', meaning: 'email', english: 'email' },
        { word: 'モニター', romaji: 'monitaa', meaning: 'moniteur', english: 'moniteur' },
        { word: 'ユニフォーム', romaji: 'yunifoomu', meaning: 'uniforme', english: 'uniforme' },
        { word: 'ライト', romaji: 'raito', meaning: 'lumière', english: 'lumière' },
        { word: 'リモコン', romaji: 'rimokon', meaning: 'télécommande', english: 'télécommande' },
        { word: 'ルール', romaji: 'ruuru', meaning: 'règle', english: 'règle' },
        { word: 'レポート', romaji: 'repooto', meaning: 'rapport', english: 'rapport' },
        { word: 'ロケット', romaji: 'roketto', meaning: 'fusée', english: 'fusée' }
    ],
    advanced: [
        { word: 'アレルギー', romaji: 'arerugii', meaning: 'allergie', english: 'allergie' },
        { word: 'イベント', romaji: 'ibento', meaning: 'événement', english: 'événement' },
        { word: 'ウォーター', romaji: 'uootaa', meaning: 'eau', english: 'eau' },
        { word: 'エコノミー', romaji: 'ekonomii', meaning: 'économie', english: 'économie' },
        { word: 'オーケストラ', romaji: 'ookesutora', meaning: 'orchestre', english: 'orchestre' },
        { word: 'カテゴリー', romaji: 'kategori', meaning: 'catégorie', english: 'catégorie' },
        { word: 'キログラム', romaji: 'kiroguramu', meaning: 'kilogramme', english: 'kilogramme' },
        { word: 'クレジット', romaji: 'kurejitto', meaning: 'crédit', english: 'crédit' },
        { word: 'ケミカル', romaji: 'kemikaru', meaning: 'chimique', english: 'chimique' },
        { word: 'コレクション', romaji: 'korekushon', meaning: 'collection', english: 'collection' },
        { word: 'サンプル', romaji: 'sanpuru', meaning: 'échantillon', english: 'échantillon' },
        { word: 'シーズン', romaji: 'shiizun', meaning: 'saison', english: 'saison' },
        { word: 'スケジュール', romaji: 'sukejuuru', meaning: 'emploi du temps', english: 'emploi du temps' },
        { word: 'セクション', romaji: 'sekushon', meaning: 'section', english: 'section' },
        { word: 'ソリューション', romaji: 'soryuushon', meaning: 'solution', english: 'solution' },
        { word: 'タイトル', romaji: 'taitoru', meaning: 'titre', english: 'titre' },
        { word: 'チーム', romaji: 'chiimu', meaning: 'équipe', english: 'équipe' },
        { word: 'ツール', romaji: 'tsuuru', meaning: 'outil', english: 'outil' },
        { word: 'テクノロジー', romaji: 'tekunorojii', meaning: 'technologie', english: 'technologie' },
        { word: 'デモンストレーション', romaji: 'demonsutoreeshon', meaning: 'démonstration', english: 'démonstration' },
        { word: 'トピック', romaji: 'topikku', meaning: 'sujet', english: 'sujet' },
        { word: 'ナビゲーション', romaji: 'nabigeeshon', meaning: 'navigation', english: 'navigation' },
        { word: 'ニュアンス', romaji: 'nyuansu', meaning: 'nuance', english: 'nuance' },
        { word: 'ネガティブ', romaji: 'negatibu', meaning: 'négatif', english: 'négatif' },
        { word: 'バランス', romaji: 'baransu', meaning: 'équilibre', english: 'équilibre' },
        { word: 'パターン', romaji: 'pataan', meaning: 'modèle', english: 'modèle' },
        { word: 'ヒューマン', romaji: 'hyuuman', meaning: 'humain', english: 'humain' },
        { word: 'ファンタジー', romaji: 'fantajii', meaning: 'fantaisie', english: 'fantaisie' },
        { word: 'フィルター', romaji: 'firutaa', meaning: 'filtre', english: 'filtre' },
        { word: 'ブレーク', romaji: 'bureeku', meaning: 'pause', english: 'pause' },
        { word: 'プラットフォーム', romaji: 'purattofoomu', meaning: 'plateforme', english: 'plateforme' },
        { word: 'プロジェクト', romaji: 'purojekuto', meaning: 'projet', english: 'projet' },
        { word: 'ベストセラー', romaji: 'besutoseraa', meaning: 'best-seller', english: 'best-seller' },
        { word: 'ペース', romaji: 'peesu', meaning: 'rythme', english: 'rythme' },
        { word: 'ボリューム', romaji: 'boryuumu', meaning: 'volume', english: 'volume' },
        { word: 'ポジション', romaji: 'pojishon', meaning: 'position', english: 'position' },
        { word: 'マネージャー', romaji: 'maneejaa', meaning: 'manager', english: 'manager' },
        { word: 'ミステリー', romaji: 'misuterii', meaning: 'mystère', english: 'mystère' },
        { word: 'メカニズム', romaji: 'mekanizumu', meaning: 'mécanisme', english: 'mécanisme' },
        { word: 'モチベーション', romaji: 'mochibeeshon', meaning: 'motivation', english: 'motivation' },
        { word: 'ユニバーシティ', romaji: 'yunibaashiti', meaning: 'université', english: 'université' },
        { word: 'ライブラリー', romaji: 'raiburarii', meaning: 'bibliothèque', english: 'bibliothèque' },
        { word: 'リソース', romaji: 'risoosu', meaning: 'ressource', english: 'ressource' },
        { word: 'ルーチン', romaji: 'ruuchin', meaning: 'routine', english: 'routine' },
        { word: 'レッスン', romaji: 'ressun', meaning: 'leçon', english: 'leçon' },
        { word: 'ロジック', romaji: 'rojikku', meaning: 'logique', english: 'logique' }
    ]
};

